(part "W2A45C103MAT2A"
    (packageRef "W2A45C103MAT2A")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Kyocera AVX")
    (property "Manufacturer_Part_Number" "W2A45C103MAT2A")
    (property "Mouser_Part_Number" "581-W2A45C103MAT2A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/AVX/W2A45C103MAT2A?qs=yRKuMHbOG1qe0RwRtAbZEg%3D%3D")
    (property "Arrow_Part_Number" "W2A45C103MAT2A")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/w2a45c103mat2a/avx")
    (property "Description" "Capacitor Arrays & Networks 50V 0.01uF 20% 4cap X7R")
    (property "Datasheet_Link" "https://static6.arrow.com/aropdfconversion/45e297553e8a3b18fcd0ed38f532e52a09efc12d/caparray.pdf")
    (property "symbolName1" "W2A45C103MAT2A")
)
