(part "CAY16-2201F4LF"
    (packageRef "RESCAX80P160X320X60-8N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "CAY16-2201F4LF")
    (property "Mouser_Part_Number" "652-CAY16-2201F4LF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/CAY16-2201F4LF?qs=tEaODSGlU8NX5flyk%2FHGvg%3D%3D")
    (property "Arrow_Part_Number" "CAY16-2201F4LF")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/cay16-2201f4lf/bourns?region=nac")
    (property "Description" "Bourns CAY16 Series 2.2k +/-1% Isolated SMT Resistor Array, 4 Resistors, 0.25W total 1206 Package Convex")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/SFDatasheet-7/sf-000140092.pdf")
    (property "symbolName1" "CAY16-2201F4LF")
)
